### ISSUE TITLE
Loading Game results in Crash

### ISSUE THREAD

**Issue by MaximoMidnight** [daemon1995/era_gaming_mods#18]
Hello,

after latest update i cant load my games.

The game directly crashes.

Crashlog is attached.

Reinstall did not help. Everything worked fine till latest update.

[HD_CRASH_LOG.txt](https://github.com/user-attachments/files/15747768/HD_CRASH_LOG.txt)

**Comment by MaximoMidnight** [comment]
disabling the HD Edition + fix + AI (ENG) Plugin solves the problem.

http://wforum.heroes35.net/showthread.php?tid=5821&page=1

The game crashed directly when clicking on LOAD. Before the update, it worked perfectly

**Comment by ERA-Projects** [comment]
It was already reported tto mod author.
