### ISSUE TITLE
WS - Neutral Units

### ISSUE THREAD

**Issue by Archer30** [daemon1995/era_gaming_mods#4]
1. The way increasing monster quantity needs to be completely rewritten! The current method is to define each monster with ID, which apparently is not compatible with extended monsters. Should be done with fight value (not AI value).
2. @PerryR-1971  or @daemon1995 are more suitable for the alternation of this script as they manage Diff Mod/ACM
3. The same changes of this script must be implemented to Diff Mod/ACM

**Comment by PerryR-1971** [comment]
We could use the same method as in Dif Mod. There I increased the quantity by monsters level. Just I had to make an exception for level 8 creatures.
