### ISSUE TITLE
Artifact Enhancement I - Orb of Inhibition feature

### ISSUE THREAD

**Issue by Archer30** [daemon1995/era_gaming_mods#8]
The Orb of Inhibition allows you to trade the Orb on **Monday** for a **random** creature of the **equipping** hero's army for a **random** ability

The interaction is messy. No one knows how he/she can use this orb without reading the script, it should be improved. 

A proposal: 
Right-clicking on the orb to have a selection dialogue for creatures in the army/abilities to choose from, similar to Emerald Tower.

Any better idea? @daemon1995 @PerryR-1971

**Comment by daemon1995** [comment]
That's actually has description.
It tells about genie inside.
Anyway only add description i support, but not direct ruling the awards
